#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# Corrected routing configuration

main:
    path: /main
    controller: App\Controller\MainController::index

create:
    path: /create
    controller: App\Controller\MainController::create

update:
    path: /update/{id}
    controller: App\Controller\MainController::update
    requirements:
        id: '\d+'  # Optional, ensures id is numeric

delete:
    path: /delete/{id}
    controller: App\Controller\MainController::delete
    requirements:
        id: '\d+'  # Optional, ensures id is numeric
